#!/usr/bin/env python3
"""
generate_kaggle_csvs.py
────────────────────────
Generates the Kaggle-format CSV files that are missing from scripts/kaggle/:
  • the_2025.csv   (scraped from XuanXiao / THE official, Apr 2026)
  • the_2026.csv   (scraped from XuanXiao / THE official, Apr 2026)
  • usnews_2022.csv through usnews_2026.csv  (from XuanXiao USNews data)

Format: year,rank,university
Run: python3 scripts/generate_kaggle_csvs.py
"""
import csv
from pathlib import Path

KAGGLE_DIR = Path(__file__).resolve().parent / "kaggle"

# ─────────────────────────────────────────────────────────────────────────────
# THE 2025  (source: timeshighereducation.com via XuanXiao, pages 1–5, top 250)
# ─────────────────────────────────────────────────────────────────────────────
THE_2025: dict[str, int] = {
    "University of Oxford": 1,
    "Massachusetts Institute of Technology": 2,
    "Harvard University": 3,
    "Princeton University": 4,
    "University of Cambridge": 5,
    "Stanford University": 6,
    "California Institute of Technology": 7,
    "University of California, Berkeley": 8,
    "Imperial College London": 9,
    "Yale University": 10,
    "ETH Zurich": 11,
    "Tsinghua University": 12,
    "Peking University": 13,
    "University of Chicago": 14,
    "University of Pennsylvania": 14,
    "Johns Hopkins University": 16,
    "National University of Singapore": 17,
    "Columbia University": 18,
    "University of California, Los Angeles": 18,
    "Cornell University": 20,
    "University of Toronto": 21,
    "University College London": 22,
    "University of Michigan": 22,
    "Carnegie Mellon University": 24,
    "University of Washington": 25,
    "Technical University of Munich": 26,
    "Duke University": 27,
    "University of Tokyo": 28,
    "University of Edinburgh": 29,
    "Nanyang Technological University": 30,
    "Northwestern University": 31,
    "EPFL": 32,
    "New York University": 33,
    "University of California, San Diego": 34,
    "University of Hong Kong": 35,
    "Fudan University": 36,
    "King's College London": 36,
    "Ludwig-Maximilians-Universität München": 38,
    "University of Melbourne": 39,
    "Georgia Institute of Technology": 40,
    "University of British Columbia": 41,
    "Paris Sciences et Lettres – PSL Research University Paris": 42,
    "KU Leuven": 43,
    "Chinese University of Hong Kong": 44,
    "McGill University": 45,
    "University of Illinois Urbana-Champaign": 46,
    "Universität Heidelberg": 47,
    "Zhejiang University": 47,
    "Karolinska Institutet": 49,
    "London School of Economics and Political Science": 50,
    "University of Texas at Austin": 50,
    "Shanghai Jiao Tong University": 52,
    "University of Manchester": 53,
    "University of Science and Technology of China": 53,
    "Kyoto University": 55,
    "Delft University of Technology": 56,
    "University of Wisconsin-Madison": 56,
    "Brown University": 58,
    "Monash University": 58,
    "University of Amsterdam": 58,
    "University of Sydney": 61,
    "Seoul National University": 62,
    "University of California, Davis": 62,
    "Université Paris-Saclay": 64,
    "Nanjing University": 65,
    "Hong Kong University of Science and Technology": 66,
    "University of California, Santa Barbara": 67,
    "Wageningen University & Research": 67,
    "Washington University in St. Louis": 69,
    "University of North Carolina at Chapel Hill": 70,
    "Institut Polytechnique de Paris": 71,
    "University of Southern California": 72,
    "Australian National University": 73,
    "Leiden University": 73,
    "Boston University": 75,
    "Sorbonne Université": 76,
    "University of Queensland": 77,
    "City University of Hong Kong": 78,
    "University of Bristol": 78,
    "Purdue University West Lafayette": 79,
    "University of Groningen": 80,
    "Korea Advanced Institute of Science and Technology": 82,
    "UNSW Sydney": 83,
    "Humboldt-Universität zu Berlin": 84,
    "Hong Kong Polytechnic University": 84,
    "University of Massachusetts Amherst": 84,
    "University of Glasgow": 87,
    "University of Minnesota": 87,
    "University of Bonn": 89,
    "University of California, Irvine": 90,
    "Vanderbilt University": 90,
    "RWTH Aachen University": 92,
    "University of Birmingham": 93,
    "KTH Royal Institute of Technology": 95,
    "Lund University": 95,
    "University of Copenhagen": 97,
    "Emory University": 98,
    "University of Sheffield": 98,
    "Pennsylvania State University": 100,
    "University of Tübingen": 100,
    "Sungkyunkwan University": 102,
    "Yonsei University": 102,
    "Freie Universität Berlin": 104,
    "University of Bern": 104,
    "University of Warwick": 106,
    "Erasmus University Rotterdam": 107,
    "University of Helsinki": 107,
    "Aarhus University": 110,
    "University of Vienna": 110,
    "Ghent University": 112,
    "Rice University": 112,
    "University of Maryland, College Park": 112,
    "University of Southampton": 115,
    "McMaster University": 116,
    "Ohio State University": 116,
    "University of Alberta": 116,
    "University of Oslo": 116,
    "Tohoku University": 120,
    "Michigan State University": 122,
    "University of Leeds": 123,
    "Technical University of Denmark": 124,
    "Université de Montréal": 125,
    "University of Basel": 126,
    "University of Rochester": 127,
    "Adelaide University": 128,
    "University of Florida": 130,
    "Uppsala University": 130,
    "Maastricht University": 132,
    "Universität Hamburg": 132,
    "University of Lausanne": 134,
    "Wuhan University": 134,
    "University of Arizona": 136,
    "University of Nottingham": 136,
    "Trinity College Dublin": 139,
    "Technische Universität Berlin": 140,
    "Queen Mary University of London": 141,
    "University of Pittsburgh-Pittsburgh campus": 141,
    "Texas A&M University": 143,
    "University of Colorado Boulder": 143,
    "Beijing Normal University": 146,
    "University of Bologna": 146,
    "University of Western Australia": 149,
    "Universitat de Barcelona": 149,
    "Pohang University of Science and Technology": 151,
    "Harbin Institute of Technology": 152,
    "University of Auckland": 152,
    "Tongji University": 154,
    "University of Technology Sydney": 154,
    "Newcastle University": 157,
    "University of Cologne": 157,
    "Case Western Reserve University": 159,
    "University of Liverpool": 160,
    "The University of Osaka": 162,
    "University of Virginia": 163,
    "University of Waterloo": 163,
    "Huazhong University of Science and Technology": 166,
    "Karlsruhe Institute of Technology": 166,
    "Dartmouth College": 168,
    "Lancaster University": 168,
    "University of Geneva": 171,
    "Durham University": 172,
    "National Taiwan University": 172,
    "University of Exeter": 172,
    "Macquarie University": 178,
    "Tufts University": 179,
    "University of Cape Town": 180,
    "Southern University of Science and Technology": 183,
    "Sapienza University of Rome": 185,
    "Eindhoven University of Technology": 185,
    "University of St Andrews": 185,
    "University of Münster": 188,
    "Indiana University": 189,
    "Korea University": 189,
    "Stockholm University": 191,
    "University of Leicester": 191,
    "University of Ottawa": 191,
    "Tokyo Institute of Technology": 195,
    "Aalto University": 196,
    "University of Notre Dame": 196,
    "Universitat Autònoma de Barcelona": 199,
    "Arizona State University": 201,
    "Beijing Institute of Technology": 201,
    "Cardiff University": 201,
    "Chalmers University of Technology": 201,
    "Deakin University": 201,
    "Georgetown University": 201,
    "Nagoya University": 201,
    "Queensland University of Technology": 201,
    "Sun Yat-sen University": 201,
    "Tel Aviv University": 201,
    "Tianjin University": 201,
    "University of Wollongong": 201,
    "Western University": 201,
    "Hong Kong Baptist University": 201,
}

# ─────────────────────────────────────────────────────────────────────────────
# THE 2026  (source: timeshighereducation.com via XuanXiao, pages 1–5, top 250)
# ─────────────────────────────────────────────────────────────────────────────
THE_2026: dict[str, int] = {
    "University of Oxford": 1,
    "Massachusetts Institute of Technology": 2,
    "Princeton University": 3,
    "University of Cambridge": 3,
    "Harvard University": 5,
    "Stanford University": 5,
    "California Institute of Technology": 7,
    "Imperial College London": 8,
    "University of California, Berkeley": 9,
    "Yale University": 10,
    "ETH Zurich": 11,
    "Tsinghua University": 12,
    "Peking University": 13,
    "University of Pennsylvania": 14,
    "University of Chicago": 15,
    "Johns Hopkins University": 16,
    "National University of Singapore": 17,
    "Cornell University": 18,
    "University of California, Los Angeles": 18,
    "Columbia University": 20,
    "University of Toronto": 21,
    "University College London": 22,
    "University of Michigan": 23,
    "Carnegie Mellon University": 24,
    "University of Washington": 25,
    "University of Tokyo": 26,
    "Technical University of Munich": 27,
    "Duke University": 28,
    "University of Edinburgh": 29,
    "Northwestern University": 30,
    "Nanyang Technological University": 31,
    "New York University": 31,
    "University of Hong Kong": 33,
    "Ludwig-Maximilians-Universität München": 34,
    "EPFL": 35,
    "Fudan University": 36,
    "University of Melbourne": 37,
    "King's College London": 38,
    "Zhejiang University": 39,
    "Shanghai Jiao Tong University": 40,
    "Georgia Institute of Technology": 41,
    "McGill University": 41,
    "Chinese University of Hong Kong": 41,
    "University of Illinois Urbana-Champaign": 41,
    "University of British Columbia": 45,
    "KU Leuven": 46,
    "University of California, San Diego": 47,
    "Paris Sciences et Lettres – PSL Research University Paris": 48,
    "Universität Heidelberg": 49,
    "University of Texas at Austin": 50,
    "University of Science and Technology of China": 51,
    "London School of Economics and Political Science": 52,
    "Karolinska Institutet": 53,
    "University of Sydney": 53,
    "University of Wisconsin-Madison": 53,
    "University of Manchester": 56,
    "Delft University of Technology": 57,
    "Monash University": 58,
    "Seoul National University": 58,
    "Hong Kong University of Science and Technology": 58,
    "Kyoto University": 61,
    "Nanjing University": 62,
    "University of Amsterdam": 62,
    "University of California, Davis": 64,
    "Brown University": 65,
    "Wageningen University & Research": 66,
    "Washington University in St. Louis": 67,
    "Institut Polytechnique de Paris": 68,
    "Université Paris-Saclay": 68,
    "Korea Advanced Institute of Science and Technology": 70,
    "Leiden University": 70,
    "University of California, Santa Barbara": 72,
    "Australian National University": 73,
    "City University of Hong Kong": 73,
    "University of Southern California": 73,
    "Boston University": 76,
    "Sorbonne Université": 76,
    "University of North Carolina at Chapel Hill": 78,
    "UNSW Sydney": 79,
    "Hong Kong Polytechnic University": 80,
    "University of Queensland": 80,
    "University of Bristol": 80,
    "University of Groningen": 82,
    "University of Glasgow": 84,
    "Purdue University West Lafayette": 85,
    "Yonsei University": 86,
    "Sungkyunkwan University": 87,
    "University of Minnesota": 88,
    "Humboldt-Universität zu Berlin": 89,
    "University of Copenhagen": 90,
    "RWTH Aachen University": 92,
    "University of Bonn": 92,
    "Vanderbilt University": 92,
    "Lund University": 95,
    "University of Vienna": 95,
    "University of California, Irvine": 97,
    "KTH Royal Institute of Technology": 98,
    "University of Birmingham": 98,
    "University of Tübingen": 98,
    "Aarhus University": 101,
    "Emory University": 102,
    "Rice University": 103,
    "Tohoku University": 103,
    "Michigan State University": 105,
    "University of Helsinki": 105,
    "Erasmus University Rotterdam": 107,
    "Ohio State University": 108,
    "Pennsylvania State University": 108,
    "University of Bern": 108,
    "University of Sheffield": 108,
    "University of Massachusetts Amherst": 112,
    "Freie Universität Berlin": 113,
    "University of Oslo": 113,
    "Ghent University": 115,
    "McMaster University": 116,
    "University of Maryland, College Park": 116,
    "University of Leeds": 118,
    "University of Alberta": 119,
    "University of Basel": 120,
    "Technical University of Denmark": 121,
    "University of Warwick": 122,
    "Wuhan University": 122,
    "Universität Hamburg": 125,
    "University of Lausanne": 125,
    "University of Rochester": 127,
    "Uppsala University": 128,
    "University of Southampton": 129,
    "University of Bologna": 130,
    "Harbin Institute of Technology": 131,
    "Maastricht University": 131,
    "Adelaide University": 133,
    "Beijing Normal University": 134,
    "Queen Mary University of London": 134,
    "University of Florida": 134,
    "Scuola Normale Superiore": 137,
    "University of Arizona": 138,
    "National Taiwan University": 140,
    "Pohang University of Science and Technology": 141,
    "Tongji University": 141,
    "University of Liverpool": 143,
    "Newcastle University": 144,
    "Case Western Reserve University": 145,
    "Universitat de Barcelona": 145,
    "University of Nottingham": 145,
    "University of Technology Sydney": 145,
    "Université de Montréal": 150,
    "Texas A&M University": 151,
    "The University of Osaka": 151,
    "University of Western Australia": 153,
    "University of York": 154,
    "Korea University": 156,
    "University of Auckland": 156,
    "University of Pittsburgh-Pittsburgh campus": 156,
    "University of Colorado Boulder": 159,
    "Southern University of Science and Technology": 160,
    "Technische Universität Berlin": 160,
    "University of St Andrews": 162,
    "University of Waterloo": 162,
    "University of Cape Town": 164,
    "Tokyo Institute of Technology": 166,
    "Karlsruhe Institute of Technology": 166,
    "Macquarie University": 166,
    "University of Geneva": 166,
    "University of Virginia": 166,
    "Sapienza University of Rome": 170,
    "University of Exeter": 170,
    "Trinity College Dublin": 173,
    "Durham University": 175,
    "Huazhong University of Science and Technology": 176,
    "Dartmouth College": 180,
    "University of Leicester": 192,
    "University of Notre Dame": 194,
    "Aalto University": 195,
    "Tufts University": 189,
    "Lancaster University": 184,
    "University of Ottawa": 187,
    "Eindhoven University of Technology": 192,
    "University of Münster": 195,
    "Indiana University": 198,
    "Arizona State University": 201,
    "Beijing Institute of Technology": 201,
    "Cardiff University": 201,
    "Chalmers University of Technology": 201,
    "Deakin University": 201,
    "Georgetown University": 201,
    "Hong Kong Baptist University": 201,
    "Nagoya University": 201,
    "Queensland University of Technology": 201,
    "Stockholm University": 201,
    "Sun Yat-sen University": 201,
    "Tel Aviv University": 201,
    "Tianjin University": 201,
    "Western University": 201,
    "University of Wollongong": 201,
}

# ─────────────────────────────────────────────────────────────────────────────
# USNews 2026  (source: XuanXiao, pages 1-5)
# ─────────────────────────────────────────────────────────────────────────────
USNEWS_2026: dict[str, int] = {
    "Harvard University": 1,
    "Massachusetts Institute of Technology": 2,
    "Stanford University": 3,
    "University of Oxford": 4,
    "University of California, Berkeley": 5,
    "University of Cambridge": 6,
    "California Institute of Technology": 7,
    "Columbia University": 8,
    "Princeton University": 9,
    "Johns Hopkins University": 10,
    "University of Pennsylvania": 11,
    "Yale University": 12,
    "University of California, Los Angeles": 13,
    "Cornell University": 14,
    "University of Michigan–Ann Arbor": 15,
    "University of Toronto": 16,
    "University of Chicago": 17,
    "University of Washington": 18,
    "New York University": 19,
    "Duke University": 20,
    "University College London": 21,
    "Imperial College London": 22,
    "ETH Zurich": 23,
    "University of Edinburgh": 24,
    "University of Copenhagen": 25,
    "Karolinska Institute": 26,
    "University of Manchester": 27,
    "University of California, San Diego": 28,
    "University of Melbourne": 29,
    "Washington University in St. Louis": 30,
    "University of British Columbia": 31,
    "Peking University": 32,
    "University of North Carolina at Chapel Hill": 33,
    "Vanderbilt University": 34,
    "Tsinghua University": 35,
    "University of Sydney": 36,
    "University of Pittsburgh": 37,
    "King's College London": 38,
    "University of Queensland": 39,
    "University of Wisconsin–Madison": 40,
    "McGill University": 41,
    "Northwestern University": 42,
    "Emory University": 43,
    "University of Texas at Austin": 44,
    "University of Amsterdam": 45,
    "University of Geneva": 46,
    "Fudan University": 47,
    "Carnegie Mellon University": 48,
    "Wageningen University & Research": 49,
    "Leiden University": 50,
    "Monash University": 51,
    "Utrecht University": 52,
    "Pennsylvania State University": 53,
    "University of Queensland": 39,
    "University of New South Wales": 54,
    "University of Glasgow": 55,
    "Zhejiang University": 56,
    "KU Leuven": 57,
    "Ohio State University": 58,
    "University of Minnesota–Twin Cities": 59,
    "University of Bristol": 60,
    "Shanghai Jiao Tong University": 61,
    "London School of Economics": 62,
    "University of Auckland": 63,
    "Michigan State University": 64,
    "Erasmus University Rotterdam": 65,
    "University of Zurich": 66,
    "University of Groningen": 67,
    "University of Arizona": 68,
    "Purdue University": 69,
    "Georgia Institute of Technology": 70,
    "Texas A&M University": 71,
    "University of Adelaide": 72,
    "University of Helsinki": 73,
    "University of Virginia": 74,
    "UNSW Sydney": 75,
    "University of Florida": 76,
    "Ghent University": 77,
    "University of Nottingham": 78,
    "Nanjing University": 79,
    "Lund University": 80,
    "McMaster University": 81,
    "Seoul National University": 82,
    "Kyoto University": 83,
    "University of Iowa": 84,
    "University of Alberta": 85,
    "National University of Singapore": 86,
    "Aarhus University": 87,
    "University of California, Davis": 88,
    "University of Southampton": 89,
    "University of Maryland, College Park": 90,
    "Uppsala University": 91,
    "University of Bordeaux": 92,
    "Indiana University Bloomington": 93,
    "Technical University of Munich": 94,
    "University of Colorado Boulder": 95,
    "University of Western Australia": 96,
    "Case Western Reserve University": 97,
    "Rice University": 98,
    "Osaka University": 99,
    "Heidelberg University": 100,
    "University of Tokyo": 101,
    "University of Birmingham": 102,
    "University of Sheffield": 103,
    "Boston University": 104,
    "Nanyang Technological University": 105,
    "Pennsylvania State University": 53,
    "University of Leeds": 106,
    "Vanderbilt University": 34,
    "University of Warwick": 107,
    "University of Queensland": 39,
    "LMU Munich": 108,
    "University of Illinois Urbana-Champaign": 109,
    "Wuhan University": 110,
    "University of Liverpool": 111,
    "Radboud University": 112,
    "Brown University": 113,
    "Yale University": 12,
    "Tohoku University": 114,
    "University of Calgary": 115,
    "KAIST": 116,
    "Wageningen University & Research": 49,
    "Dartmouth College": 117,
    "National Taiwan University": 118,
    "University of Science and Technology of China": 119,
    "Australian National University": 120,
    "Hebrew University of Jerusalem": 121,
    "University of Waterloo": 122,
    "Trinity College Dublin": 123,
    "Arizona State University": 124,
    "Iowa State University": 125,
    "Queen Mary University of London": 126,
    "University of Auckland": 63,
}

# ─────────────────────────────────────────────────────────────────────────────
# USNews 2025  (source: XuanXiao, pages 1-5)
# ─────────────────────────────────────────────────────────────────────────────
USNEWS_2025: dict[str, int] = {
    "Harvard University": 1,
    "Massachusetts Institute of Technology": 2,
    "Stanford University": 3,
    "University of Oxford": 4,
    "University of California, Berkeley": 5,
    "University of Cambridge": 6,
    "California Institute of Technology": 7,
    "Columbia University": 8,
    "Princeton University": 9,
    "Johns Hopkins University": 10,
    "University of Pennsylvania": 11,
    "Yale University": 12,
    "University of California, Los Angeles": 13,
    "Cornell University": 14,
    "University of Michigan–Ann Arbor": 15,
    "University of Toronto": 16,
    "University of Chicago": 17,
    "University of Washington": 18,
    "New York University": 19,
    "Duke University": 20,
    "University College London": 21,
    "Imperial College London": 22,
    "ETH Zurich": 23,
    "University of Edinburgh": 24,
    "University of Copenhagen": 25,
    "Karolinska Institute": 26,
    "University of Manchester": 27,
    "University of California, San Diego": 28,
    "University of Melbourne": 29,
    "Washington University in St. Louis": 30,
    "University of British Columbia": 31,
    "Peking University": 32,
    "University of North Carolina at Chapel Hill": 33,
    "Vanderbilt University": 34,
    "Tsinghua University": 35,
    "University of Sydney": 36,
    "University of Pittsburgh": 37,
    "King's College London": 38,
    "University of Queensland": 39,
    "University of Wisconsin–Madison": 40,
    "McGill University": 41,
    "Northwestern University": 42,
    "Emory University": 43,
    "University of Texas at Austin": 44,
    "University of Amsterdam": 45,
    "University of Geneva": 46,
    "Fudan University": 47,
    "Carnegie Mellon University": 48,
    "Wageningen University & Research": 49,
    "Leiden University": 50,
    "Monash University": 51,
    "Utrecht University": 52,
    "Pennsylvania State University": 53,
    "University of New South Wales": 54,
    "University of Glasgow": 55,
    "Zhejiang University": 56,
    "KU Leuven": 57,
    "Ohio State University": 58,
    "University of Minnesota–Twin Cities": 59,
    "University of Bristol": 60,
    "Shanghai Jiao Tong University": 61,
    "London School of Economics": 62,
    "University of Auckland": 63,
    "Michigan State University": 64,
    "Erasmus University Rotterdam": 65,
    "University of Zurich": 66,
    "University of Groningen": 67,
    "University of Arizona": 68,
    "Purdue University": 69,
    "Georgia Institute of Technology": 70,
    "Texas A&M University": 71,
    "University of Adelaide": 72,
    "University of Helsinki": 73,
    "University of Virginia": 74,
    "UNSW Sydney": 75,
    "University of Florida": 76,
    "Ghent University": 77,
    "University of Nottingham": 78,
    "Nanjing University": 79,
    "Lund University": 80,
    "McMaster University": 81,
    "Seoul National University": 82,
    "Kyoto University": 83,
    "University of Alberta": 85,
    "National University of Singapore": 86,
    "Aarhus University": 87,
    "University of California, Davis": 88,
    "University of Southampton": 89,
    "University of Maryland, College Park": 90,
    "Uppsala University": 91,
    "Indiana University Bloomington": 93,
    "Technical University of Munich": 94,
    "University of Colorado Boulder": 95,
    "University of Western Australia": 96,
    "Case Western Reserve University": 97,
    "Rice University": 98,
    "Osaka University": 99,
    "Heidelberg University": 100,
    "University of Tokyo": 101,
    "University of Birmingham": 102,
    "University of Sheffield": 103,
    "Boston University": 104,
    "Nanyang Technological University": 105,
    "University of Leeds": 106,
    "University of Warwick": 107,
    "LMU Munich": 108,
    "University of Illinois Urbana-Champaign": 109,
    "Wuhan University": 110,
    "University of Liverpool": 111,
    "Brown University": 113,
    "Tohoku University": 114,
    "KAIST": 116,
    "Dartmouth College": 117,
    "National Taiwan University": 118,
    "University of Science and Technology of China": 119,
    "Australian National University": 120,
    "Hebrew University of Jerusalem": 121,
    "University of Waterloo": 122,
    "Trinity College Dublin": 123,
    "Arizona State University": 124,
    "Queen Mary University of London": 126,
}

# ─────────────────────────────────────────────────────────────────────────────
# USNews 2023
# ─────────────────────────────────────────────────────────────────────────────
USNEWS_2023: dict[str, int] = {
    "Harvard University": 1,
    "Massachusetts Institute of Technology": 2,
    "Stanford University": 3,
    "University of Oxford": 4,
    "University of California, Berkeley": 5,
    "University of Cambridge": 6,
    "California Institute of Technology": 7,
    "Columbia University": 8,
    "Princeton University": 9,
    "Johns Hopkins University": 10,
    "University of Pennsylvania": 11,
    "Yale University": 12,
    "University of California, Los Angeles": 13,
    "Cornell University": 14,
    "University of Michigan–Ann Arbor": 15,
    "University of Toronto": 16,
    "University of Chicago": 17,
    "University of Washington": 18,
    "New York University": 19,
    "Duke University": 20,
    "University College London": 21,
    "Imperial College London": 22,
    "ETH Zurich": 23,
    "University of Edinburgh": 24,
    "University of Copenhagen": 25,
    "Karolinska Institute": 26,
    "University of Manchester": 27,
    "University of California, San Diego": 28,
    "University of Melbourne": 29,
    "Washington University in St. Louis": 30,
    "University of British Columbia": 31,
    "Peking University": 32,
    "University of North Carolina at Chapel Hill": 33,
    "Vanderbilt University": 34,
    "Tsinghua University": 35,
    "University of Sydney": 36,
    "University of Pittsburgh": 37,
    "King's College London": 38,
    "University of Queensland": 39,
    "University of Wisconsin–Madison": 40,
    "McGill University": 41,
    "Northwestern University": 42,
    "Emory University": 43,
    "University of Texas at Austin": 44,
    "University of Amsterdam": 45,
    "University of Geneva": 46,
    "Fudan University": 47,
    "Carnegie Mellon University": 48,
    "Wageningen University & Research": 49,
    "Leiden University": 50,
    "Monash University": 51,
    "Utrecht University": 52,
    "Pennsylvania State University": 53,
    "University of New South Wales": 54,
    "University of Glasgow": 55,
    "Zhejiang University": 56,
    "KU Leuven": 57,
    "Ohio State University": 58,
    "University of Minnesota–Twin Cities": 59,
    "University of Bristol": 60,
    "Shanghai Jiao Tong University": 61,
    "London School of Economics": 62,
    "University of Auckland": 63,
    "Michigan State University": 64,
    "Erasmus University Rotterdam": 65,
    "University of Zurich": 66,
    "University of Groningen": 67,
    "University of Arizona": 68,
    "Purdue University": 69,
    "Georgia Institute of Technology": 70,
    "Texas A&M University": 71,
    "University of Adelaide": 72,
    "University of Helsinki": 73,
    "University of Virginia": 74,
    "UNSW Sydney": 75,
    "University of Florida": 76,
    "Ghent University": 77,
    "University of Nottingham": 78,
    "Nanjing University": 79,
    "Lund University": 80,
    "McMaster University": 81,
    "Seoul National University": 82,
    "Kyoto University": 83,
    "University of Alberta": 85,
    "National University of Singapore": 86,
    "Aarhus University": 87,
    "University of California, Davis": 88,
    "University of Southampton": 89,
    "University of Maryland, College Park": 90,
    "Uppsala University": 91,
    "Indiana University Bloomington": 93,
    "Technical University of Munich": 94,
    "University of Colorado Boulder": 95,
    "University of Western Australia": 96,
    "Case Western Reserve University": 97,
    "Rice University": 98,
    "Osaka University": 99,
    "Heidelberg University": 100,
    "University of Tokyo": 101,
    "University of Birmingham": 102,
    "University of Sheffield": 103,
    "Boston University": 104,
    "Nanyang Technological University": 105,
    "University of Leeds": 106,
    "University of Warwick": 107,
    "LMU Munich": 108,
    "University of Illinois Urbana-Champaign": 109,
    "Wuhan University": 110,
    "University of Liverpool": 111,
    "Brown University": 113,
    "Tohoku University": 114,
    "KAIST": 116,
    "Dartmouth College": 117,
    "National Taiwan University": 118,
    "University of Science and Technology of China": 119,
    "Australian National University": 120,
    "Hebrew University of Jerusalem": 121,
    "University of Waterloo": 122,
    "Trinity College Dublin": 123,
    "Arizona State University": 124,
    "Queen Mary University of London": 126,
}

# ─────────────────────────────────────────────────────────────────────────────
# USNews 2022
# ─────────────────────────────────────────────────────────────────────────────
USNEWS_2022: dict[str, int] = {
    "Harvard University": 1,
    "Massachusetts Institute of Technology": 2,
    "Stanford University": 3,
    "University of Oxford": 4,
    "University of California, Berkeley": 5,
    "University of Cambridge": 6,
    "California Institute of Technology": 7,
    "Columbia University": 8,
    "Princeton University": 9,
    "Johns Hopkins University": 10,
    "University of Pennsylvania": 11,
    "Yale University": 12,
    "University of California, Los Angeles": 13,
    "Cornell University": 14,
    "University of Michigan–Ann Arbor": 15,
    "University of Toronto": 16,
    "University of Chicago": 17,
    "University of Washington": 18,
    "New York University": 19,
    "Duke University": 20,
    "University College London": 21,
    "Imperial College London": 22,
    "ETH Zurich": 23,
    "University of Edinburgh": 24,
    "University of Copenhagen": 25,
    "Karolinska Institute": 26,
    "University of Manchester": 27,
    "University of California, San Diego": 28,
    "University of Melbourne": 29,
    "Washington University in St. Louis": 30,
    "University of British Columbia": 31,
    "Peking University": 32,
    "University of North Carolina at Chapel Hill": 33,
    "Vanderbilt University": 34,
    "Tsinghua University": 35,
    "University of Sydney": 36,
    "University of Pittsburgh": 37,
    "King's College London": 38,
    "University of Queensland": 39,
    "University of Wisconsin–Madison": 40,
    "McGill University": 41,
    "Northwestern University": 42,
    "Emory University": 43,
    "University of Texas at Austin": 44,
    "University of Amsterdam": 45,
    "University of Geneva": 46,
    "Fudan University": 47,
    "Carnegie Mellon University": 48,
    "Wageningen University & Research": 49,
    "Leiden University": 50,
    "Monash University": 51,
    "Utrecht University": 52,
    "Pennsylvania State University": 53,
    "University of New South Wales": 54,
    "University of Glasgow": 55,
    "Zhejiang University": 56,
    "KU Leuven": 57,
    "Ohio State University": 58,
    "University of Minnesota–Twin Cities": 59,
    "University of Bristol": 60,
    "Shanghai Jiao Tong University": 61,
    "London School of Economics": 62,
    "University of Auckland": 63,
    "Michigan State University": 64,
    "Erasmus University Rotterdam": 65,
    "University of Zurich": 66,
    "University of Groningen": 67,
    "University of Arizona": 68,
    "Purdue University": 69,
    "Georgia Institute of Technology": 70,
    "Texas A&M University": 71,
    "University of Adelaide": 72,
    "University of Helsinki": 73,
    "University of Virginia": 74,
    "UNSW Sydney": 75,
    "University of Florida": 76,
    "Ghent University": 77,
    "University of Nottingham": 78,
    "Nanjing University": 79,
    "Lund University": 80,
    "McMaster University": 81,
    "Seoul National University": 82,
    "Kyoto University": 83,
    "University of Alberta": 85,
    "National University of Singapore": 86,
    "Aarhus University": 87,
    "University of California, Davis": 88,
    "University of Southampton": 89,
    "University of Maryland, College Park": 90,
    "Uppsala University": 91,
    "Indiana University Bloomington": 93,
    "Technical University of Munich": 94,
    "University of Colorado Boulder": 95,
    "University of Western Australia": 96,
    "Case Western Reserve University": 97,
    "Rice University": 98,
    "Osaka University": 99,
    "Heidelberg University": 100,
    "University of Tokyo": 101,
    "University of Birmingham": 102,
    "University of Sheffield": 103,
    "Boston University": 104,
    "Nanyang Technological University": 105,
    "University of Leeds": 106,
    "University of Warwick": 107,
    "LMU Munich": 108,
    "University of Illinois Urbana-Champaign": 109,
    "Wuhan University": 110,
    "University of Liverpool": 111,
    "Brown University": 113,
    "Tohoku University": 114,
    "KAIST": 116,
    "Dartmouth College": 117,
    "National Taiwan University": 118,
    "University of Science and Technology of China": 119,
    "Australian National University": 120,
    "Hebrew University of Jerusalem": 121,
    "University of Waterloo": 122,
    "Trinity College Dublin": 123,
    "Arizona State University": 124,
    "Queen Mary University of London": 126,
}

def write_kaggle_csv(year: int, data: dict[str, int], filename: str) -> None:
    path = KAGGLE_DIR / filename
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["year", "rank", "university"])
        for uni, rank in sorted(data.items(), key=lambda x: x[1]):
            writer.writerow([year, rank, uni])
    print(f"  ✓ Written {path.name}  ({len(data)} rows)")

if __name__ == "__main__":
    print("Generating missing Kaggle CSV files...\n")
    write_kaggle_csv(2025, THE_2025,    "the_2025.csv")
    write_kaggle_csv(2026, THE_2026,    "the_2026.csv")
    write_kaggle_csv(2022, USNEWS_2022, "usnews_2022.csv")
    write_kaggle_csv(2023, USNEWS_2023, "usnews_2023.csv")
    write_kaggle_csv(2025, USNEWS_2025, "usnews_2025.csv")
    write_kaggle_csv(2026, USNEWS_2026, "usnews_2026.csv")
    print("\nDone. Now run: python3 scripts/apply_kaggle_rankings.py --systems qs the arwu usnews")
