#!/usr/bin/env python3
"""
Update rankTimes_2025 and rankTimes_2026 in universities.csv using data
scraped from xuanxiao.org (THE World University Rankings 2025 and 2026).
Source: https://www.timeshighereducation.com (via XuanXiao mirror)
"""

import csv, sys, os

CSV_PATH = os.path.join(os.path.dirname(__file__), "../cinfo/universities.csv")

# ── THE 2025 (pages 1–5, ranks 1–250) ────────────────────────────────────────
THE_2025 = {
    "University of Oxford": 1,
    "Massachusetts Institute of Technology": 2,
    "Harvard University": 3,
    "Princeton University": 4,
    "University of Cambridge": 5,
    "Stanford University": 6,
    "California Institute of Technology": 7,
    "University of California, Berkeley": 8,
    "Imperial College London": 9,
    "Yale University": 10,
    "ETH Zurich": 11,
    "Tsinghua University": 12,
    "Peking University": 13,
    "University of Chicago": 14,
    "University of Pennsylvania": 14,
    "Johns Hopkins University": 16,
    "National University of Singapore": 17,
    "Columbia University": 18,
    "University of California, Los Angeles": 18,
    "Cornell University": 20,
    "University of Toronto": 21,
    "University College London": 22,
    "University of Michigan–Ann Arbor": 22,
    "Carnegie Mellon University": 24,
    "University of Washington": 25,
    "Technical University of Munich": 26,
    "Duke University": 27,
    "University of Tokyo": 28,
    "University of Edinburgh": 29,
    "Nanyang Technological University": 30,
    "Northwestern University": 31,
    "EPFL": 32,
    "New York University": 33,
    "University of California, San Diego": 34,
    "University of Hong Kong": 35,
    "Fudan University": 36,
    "King's College London": 36,
    "LMU Munich": 38,
    "University of Melbourne": 39,
    "Georgia Institute of Technology": 40,
    "University of British Columbia": 41,
    "PSL University": 42,
    "KU Leuven": 43,
    "Chinese University of Hong Kong": 44,
    "McGill University": 45,
    "University of Illinois Urbana-Champaign": 46,
    "Heidelberg University": 47,
    "Zhejiang University": 47,
    "Karolinska Institute": 49,
    "London School of Economics": 50,
    "University of Texas at Austin": 50,
    "Shanghai Jiao Tong University": 52,
    "University of Manchester": 53,
    "University of Science and Technology of China": 53,
    "Kyoto University": 55,
    "Delft University of Technology": 56,
    "University of Wisconsin–Madison": 56,
    "Brown University": 58,
    "Monash University": 58,
    "University of Amsterdam": 58,
    "University of Sydney": 61,
    "Seoul National University": 62,
    "University of California, Davis": 62,
    "Université Paris-Saclay": 64,
    "Nanjing University": 65,
    "HKUST": 66,
    "University of California, Santa Barbara": 67,
    "Wageningen University & Research": 67,
    "Washington University in St. Louis": 69,
    "University of North Carolina at Chapel Hill": 70,
    "Institut Polytechnique de Paris": 71,
    "University of Southern California": 72,
    "Australian National University": 73,
    "Leiden University": 73,
    "Boston University": 75,
    "Sorbonne University": 76,
    "University of Queensland": 77,
    "City University of Hong Kong": 78,
    "University of Bristol": 78,
    "Purdue University": 79,
    "University of Groningen": 80,
    "KAIST": 82,
    "University of New South Wales": 83,
    "Humboldt University of Berlin": 84,
    "Hong Kong Polytechnic University": 84,
    "University of Massachusetts Amherst": 84,
    "University of Glasgow": 87,
    "University of Minnesota–Twin Cities": 87,
    "University of Bonn": 89,
    "University of California, Irvine": 90,
    "Vanderbilt University": 90,
    "RWTH Aachen University": 92,
    "University of Birmingham": 93,
    "KTH Royal Institute of Technology": 95,
    "Lund University": 95,
    "University of Copenhagen": 97,
    "Emory University": 98,
    "University of Sheffield": 98,
    "Pennsylvania State University": 100,
    "University of Tübingen": 100,
    "Sungkyunkwan University": 102,
    "Yonsei University": 102,
    "Free University of Berlin": 104,
    "University of Bern": 104,
    "University of Warwick": 106,
    "Erasmus University Rotterdam": 107,
    "University of Helsinki": 107,
    "Aarhus University": 110,
    "University of Vienna": 110,
    "Ghent University": 112,
    "University of Maryland, College Park": 112,
    "University of Southampton": 115,
    "McMaster University": 116,
    "Ohio State University": 116,
    "University of Alberta": 116,
    "University of Oslo": 116,
    "Tohoku University": 120,
    "Michigan State University": 122,
    "University of Leeds": 123,
    "Technical University of Denmark": 124,
    "University of Adelaide": 128,
    "University of Florida": 130,
    "Uppsala University": 130,
    "Maastricht University": 132,
    "University of Hamburg": 132,
    "University of Lausanne": 134,
    "Wuhan University": 134,
    "University of Arizona": 136,
    "University of Nottingham": 136,
    "Trinity College Dublin": 139,
    "Technical University of Berlin": 140,
    "Queen Mary University of London": 141,
    "Radboud University Nijmegen": 143,
    "Texas A&M University": 143,
    "University of Colorado Boulder": 143,
    "Beijing Normal University": 146,
    "University of Bologna": 146,
    "University of Western Australia": 149,
    "University of Barcelona": 149,
    "POSTECH": 151,
    "Harbin Institute of Technology": 152,
    "University of Auckland": 152,
    "Tongji University": 154,
    "University of Technology Sydney": 154,
    "Newcastle University": 157,
    "University of Cologne": 157,
    "Case Western Reserve University": 159,
    "University of Liverpool": 160,
    "Osaka University": 162,
    "University of Virginia": 163,
    "University of Waterloo": 163,
    "Huazhong University of Science and Technology": 166,
    "Karlsruhe Institute of Technology": 166,
    "Dartmouth College": 168,
    "Lancaster University": 168,
    "University of Geneva": 171,
    "Durham University": 172,
    "National Taiwan University": 172,
    "University of Exeter": 172,
    "Macquarie University": 178,
    "Tufts University": 179,
    "University of Cape Town": 180,
    "Southern University of Science and Technology": 183,
    "University of St Andrews": 185,
    "University of Münster": 188,
    "Indiana University Bloomington": 189,
    "Korea University": 189,
    "Stockholm University": 191,
    "University of Leicester": 191,
    "University of Ottawa": 191,
    "Tokyo Institute of Technology": 195,
    "Universitat Autònoma de Barcelona": 199,
    "Rice University": 112,
    "University of Pittsburgh": 141,
    "Sapienza University of Rome": 185,
    "Eindhoven University of Technology": 185,
    "Aalto University": 196,
    "University of Notre Dame": 196,
    # 201-250 band
    "Arizona State University": 201,
    "Beijing Institute of Technology": 201,
    "Cardiff University": 201,
    "Chalmers University of Technology": 201,
    "Deakin University": 201,
    "Georgetown University": 201,
    "Queensland University of Technology": 201,
    "Western University": 201,
    "Tel Aviv University": 201,
    "Sun Yat-sen University": 201,
    "Nagoya University": 201,
    "Tianjin University": 201,
    "University of Wollongong": 201,
    "Hong Kong Baptist University": 201,
}

# ── THE 2026 (pages 1–5, ranks 1–250) ────────────────────────────────────────
THE_2026 = {
    "University of Oxford": 1,
    "Massachusetts Institute of Technology": 2,
    "Princeton University": 3,
    "University of Cambridge": 3,
    "Harvard University": 5,
    "Stanford University": 5,
    "California Institute of Technology": 7,
    "Imperial College London": 8,
    "University of California, Berkeley": 9,
    "Yale University": 10,
    "ETH Zurich": 11,
    "Tsinghua University": 12,
    "Peking University": 13,
    "University of Pennsylvania": 14,
    "University of Chicago": 15,
    "Johns Hopkins University": 16,
    "National University of Singapore": 17,
    "Cornell University": 18,
    "University of California, Los Angeles": 18,
    "Columbia University": 20,
    "University of Toronto": 21,
    "University College London": 22,
    "University of Michigan–Ann Arbor": 23,
    "Carnegie Mellon University": 24,
    "University of Washington": 25,
    "University of Tokyo": 26,
    "Technical University of Munich": 27,
    "Duke University": 28,
    "University of Edinburgh": 29,
    "Northwestern University": 30,
    "Nanyang Technological University": 31,
    "New York University": 31,
    "University of Hong Kong": 33,
    "LMU Munich": 34,
    "EPFL": 35,
    "Fudan University": 36,
    "University of Melbourne": 37,
    "King's College London": 38,
    "Zhejiang University": 39,
    "Shanghai Jiao Tong University": 40,
    "Georgia Institute of Technology": 41,
    "McGill University": 41,
    "Chinese University of Hong Kong": 41,
    "University of Illinois Urbana-Champaign": 41,
    "University of British Columbia": 45,
    "KU Leuven": 46,
    "University of California, San Diego": 47,
    "PSL University": 48,
    "Heidelberg University": 49,
    "University of Texas at Austin": 50,
    "University of Science and Technology of China": 51,
    "London School of Economics": 52,
    "Karolinska Institute": 53,
    "University of Sydney": 53,
    "University of Wisconsin–Madison": 53,
    "University of Manchester": 56,
    "Delft University of Technology": 57,
    "Monash University": 58,
    "Seoul National University": 58,
    "HKUST": 58,
    "Kyoto University": 61,
    "Nanjing University": 62,
    "University of Amsterdam": 62,
    "University of California, Davis": 64,
    "Brown University": 65,
    "Wageningen University & Research": 66,
    "Washington University in St. Louis": 67,
    "Institut Polytechnique de Paris": 68,
    "Université Paris-Saclay": 68,
    "KAIST": 70,
    "Leiden University": 70,
    "University of California, Santa Barbara": 72,
    "Australian National University": 73,
    "City University of Hong Kong": 73,
    "University of Southern California": 73,
    "Boston University": 76,
    "Sorbonne University": 76,
    "University of North Carolina at Chapel Hill": 78,
    "University of New South Wales": 79,
    "Hong Kong Polytechnic University": 80,
    "University of Queensland": 80,
    "University of Bristol": 80,
    "University of Groningen": 82,
    "University of Glasgow": 84,
    "Purdue University": 85,
    "Yonsei University": 86,
    "Sungkyunkwan University": 87,
    "University of Minnesota–Twin Cities": 88,
    "Humboldt University of Berlin": 89,
    "University of Copenhagen": 90,
    "RWTH Aachen University": 92,
    "University of Bonn": 92,
    "Vanderbilt University": 92,
    "Lund University": 95,
    "University of Vienna": 95,
    "University of California, Irvine": 97,
    "KTH Royal Institute of Technology": 98,
    "University of Birmingham": 98,
    "University of Tübingen": 98,
    "Aarhus University": 101,
    "Emory University": 102,
    "Rice University": 103,
    "Tohoku University": 103,
    "Michigan State University": 105,
    "University of Helsinki": 105,
    "Erasmus University Rotterdam": 107,
    "Ohio State University": 108,
    "Pennsylvania State University": 108,
    "University of Bern": 108,
    "University of Sheffield": 108,
    "University of Massachusetts Amherst": 112,
    "Free University of Berlin": 113,
    "University of Oslo": 113,
    "Ghent University": 115,
    "McMaster University": 116,
    "University of Maryland, College Park": 116,
    "University of Leeds": 118,
    "University of Alberta": 119,
    "University of Basel": 120,
    "Technical University of Denmark": 121,
    "University of Warwick": 122,
    "Wuhan University": 122,
    "University of Hamburg": 125,
    "University of Lausanne": 125,
    "University of Rochester": 127,
    "Uppsala University": 128,
    "University of Southampton": 129,
    "University of Bologna": 130,
    "Harbin Institute of Technology": 131,
    "Maastricht University": 131,
    "University of Adelaide": 133,
    "Beijing Normal University": 134,
    "Queen Mary University of London": 134,
    "University of Florida": 134,
    "University of Arizona": 138,
    "National Taiwan University": 140,
    "POSTECH": 141,
    "Tongji University": 141,
    "University of Liverpool": 143,
    "Newcastle University": 144,
    "Case Western Reserve University": 145,
    "University of Barcelona": 145,
    "University of Nottingham": 145,
    "University of Technology Sydney": 145,
    "University of Montréal": 150,
    "Texas A&M University": 151,
    "Osaka University": 151,
    "University of Western Australia": 153,
    "Radboud University Nijmegen": 154,
    "Korea University": 156,
    "University of Auckland": 156,
    "University of Colorado Boulder": 159,
    "Southern University of Science and Technology": 160,
    "Technical University of Berlin": 160,
    "University of St Andrews": 162,
    "University of Waterloo": 162,
    "University of Cape Town": 164,
    "University of Cologne": 164,
    "Tokyo Institute of Technology": 166,
    "Karlsruhe Institute of Technology": 166,
    "Macquarie University": 166,
    "University of Geneva": 166,
    "University of Virginia": 166,
    "Sapienza University of Rome": 170,
    "University of Exeter": 170,
    "Trinity College Dublin": 173,
    "Durham University": 175,
    "Huazhong University of Science and Technology": 176,
    "Dartmouth College": 180,
    "Medical University of Vienna": 181,
    "University of California, Santa Cruz": 181,
    "Universitat Autònoma de Barcelona": 183,
    "Lancaster University": 184,
    "University of Ottawa": 187,
    "Tufts University": 189,
    "University of Notre Dame": 194,
    "University of Calgary": 200,
    "University of Pittsburgh": 156,
    # 201-250 band
    "Arizona State University": 201,
    "Beijing Institute of Technology": 201,
    "Cardiff University": 201,
    "Chalmers University of Technology": 201,
    "Deakin University": 201,
    "Georgetown University": 201,
    "Hong Kong Baptist University": 201,
    "Nagoya University": 201,
    "Queensland University of Technology": 201,
    "Stockholm University": 201,
    "Sun Yat-sen University": 201,
    "Tel Aviv University": 201,
    "Tianjin University": 201,
    "Western University": 201,
    "University of Wollongong": 201,
}

def update_col(rows, col, data, fieldnames):
    if col not in fieldnames:
        print(f"ERROR: column '{col}' not found")
        return 0, 0
    updated = unchanged = 0
    for row in rows:
        name = row["name"]
        if name in data:
            new_val = str(data[name])
            old_val = row[col].strip()
            if old_val != new_val:
                row[col] = new_val
                updated += 1
                print(f"  {col}  {name:55s}  {old_val or '(empty)':>8} → {new_val}")
            else:
                unchanged += 1
    return updated, unchanged

def main():
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        rows = list(reader)

    u25, s25 = update_col(rows, "rankTimes_2025", THE_2025, fieldnames)
    u26, s26 = update_col(rows, "rankTimes_2026", THE_2026, fieldnames)

    with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_ALL)
        writer.writeheader()
        writer.writerows(rows)

    print(f"\n✓ rankTimes_2025: {u25} updated, {s25} unchanged")
    print(f"✓ rankTimes_2026: {u26} updated, {s26} unchanged")

if __name__ == "__main__":
    main()
